### ISSUE TITLE
video recording function

### ISSUE THREAD

**Issue by alezi58** [hkr/fuji-cam-wifi-tool#14]
The project is very interesting! I connected my Fuji X-T30 using this program. But Fuji Camera Remote allows you to shoot video, not just photos. Is it possible to add such a command here?
I want to connect my Fuji X-T30 to a DJI Ronin-SC for video recording. Unfortunately, Fuji does not provide such support :( In the older model, this is done via USB tethering, but there is no video recording in the SDK! I would like to use the USB (from the DJI side) - WiFi (from the Fuji side) bridge. Fuji does not yet support SDK

**Comment by mzealey** [comment]
I have done this in a forked repo https://github.com/mzealey/fuji-cam-wifi-tool - start_record, stop_record

**Comment by Chrisedmo** [comment]
Ah nice @mzealey I've been looking for something like this!

**Comment by hkr** [comment]
I merged  https://github.com/mzealey/fuji-cam-wifi-tool but I have not tested video recording myself.
