### ISSUE TITLE
Is it possibe to increase the stream resolution?

### ISSUE THREAD

**Issue by etkayapar** [hkr/fuji-cam-wifi-tool#17]
I tried to read the code to understand this but I was not able to. Is it possible to increase the resolution when using `stream_cv` with a videodevice under linux? It is by default 640x480. I tried to build `v4l2loopback` with changed source code for increasing the width and the height of the device then reisnerting the module, but It doesn't seem to change the final resolution. I am using @mzealey 's fork at the moment. Thank you both for this amazing tool!

**Comment by mzealey** [comment]
i think that's all that the camera streams at unfortunately

**Comment by etkayapar** [comment]
what I was afraid of. Thanks!
