### ISSUE TITLE
X-T2 requires newer version

### ISSUE THREAD

**Issue by winkj** [hkr/fuji-cam-wifi-tool#2]
Hi there, I just discovered this and wanted to try it out. Using an X-T2, I get an error when connecting:

I get the prompt whether I want to connect to "HackedClient" so the initial handshake seems to work, but afterwards I get a message saying
"The app is previous version
 Upgrade app to latest version"

I understand you've been busy with other stuff, so this is just FYI (and for others interested in trying this on an X-T2).

**Comment by hkr** [comment]
Thanks for letting me know.
I just updated the Android app that I'm using. So far I have not found any differences, but might have missed something. Unfortunately I don't have access to a X-T2 camera.
The log that fuji_cam_wifi_tool prints to stdout might help, because it dumps most of the data that is sent and received.

**Comment by xaphod** [comment]
I have an X-T2 and have made dumps with wireshark 2.x from the iOS Fuji app as it does live view, fires shutter, etc. Also did one of receive mode. I can send these to whoever would like them - tag me in this thread. Happy to make new ones if it aint too complicated.

**Comment by fjolnir** [comment]
@xaphod I'd love to see those!

**Comment by hkr** [comment]
@xaphod sure, send them over, thx :)

**Comment by xaphod** [comment]
Weird, i'm not getting notifications from github anymore.

OK I posted them, here:
http://www.fuzzymunchkin.com/tmp/fuji-connect-receive-1img-selected-from-cam.pcapng.gz
http://www.fuzzymunchkin.com/tmp/fuji-connect-take1-withliveview.pcapng.gz
http://www.fuzzymunchkin.com/tmp/fuji-shoot1-then-try-to-DL-another-fromplaymode-appcrash.pcapng.gz

I'm still looking for any SDK for Fuji that maps more codes, ie. what turns on live view, what turns it off etc... anyone found something?

**Comment by tengelmeier** [comment]
I heard the SDK is available to companies by request to the local Fuji headquarter. Unfortunately single developers don't qualify (in contrary to Nikon and Canon).

**Comment by xaphod** [comment]
I requested as a company. No response.

**Comment by Fidi** [comment]
Hi, I just had some free time and was able to fix the error on the X-T2. However, I don't have access to the X-T10, so you should probably check if this does not break anything.
Everything else seems to be working on the X-T2 just fine, now.

**Comment by mrosseel** [comment]
Hi,

I can test with my X-T1.
When you say everything else, did you add some features or do you mean the
original features now work?

**Comment by Fidi** [comment]
I was referring to the original features. I'm currently working my way into the code and I will then try to add some new features.

**Comment by lupino3** [comment]
FYI I have just done a quick test with an X-T10 and I can both connect and take a picture.

**Comment by glyons** [comment]
I got it to connect to X-E3 but have the problem that's it complains the app needs to be upgraded. I guess the same issue @Fidi was having.  Any idea how to get the registration codes [https://github.com/hkr/fuji-cam-wifi-tool/commit/b5216a113f9e32c54bd54d848535fc9d85c34745](url)
