### ISSUE TITLE
Protocol information

### ISSUE THREAD

**Issue by tihoulas** [hkr/fuji-cam-wifi-tool#5]
Hi,

I am working on making this software connect with my X-T2 in receive mode. So far, my code, while working, is to ugly to commit. However, I have found new information on the protocol used to request a picture. In commands.cpp, you provide the following :

```
// get actual image in full size
//    18:00:00:00: 01:00:1b:10: 30:00:00:00: 01:00:00:00: 00:00:00:00:
//    68:81:08:00 // last one is image id?
```
I would like to correct this. In fact, the request is : 
```
// get actual image in full size
//    18:00:00:00: 01:00:1b:10: 30:00:00:00: 01:00:00:00:
//    00:00:00:00: // offset from the begining of the picture
//    68:81:08:00 // size of the picture chunk asked
```

Changing the offset and the size, you can choose to download the picture in multiple parts. The camera will know when the whole picture is sent.

**Comment by reetp** [comment]
Any further info on this ?
I'd like to be able to send/receive pix to store on my linux server.
Doesn't need anything complicated... just the ability to drop them to a directory.

**Comment by msmeissn** [comment]
This seems PTP protocol. 101b is GetPartialObject , id, startoffset, length
