### ISSUE TITLE
Bounty: control shutter speed

### ISSUE THREAD

**Issue by mrosseel** [hkr/fuji-cam-wifi-tool#8]
**Bounty amount**: 100 euro, payable in paypal or bitcoin
**Bounty deadline**: 1st of July 2017 (can be optionally extended if you're almost finished)
**Context**: I will photograph the USA eclipse this summer, and if the Fuji XT-1 is not remote controllable, I'll have to buy myself a second hand canon/nikon. I'd rather spend the money on getting remote control for all fuji users!
Concretely, I will take automatic sequences of all shutter speeds between 1/32000s and 2sec over and over in the 2 minutes of the eclipse. This will be used to do kind of HDR processing afterwards.

**Specs**:
- fuji-cam-wifi-tool control of all possible shutter speeds (1/32000 to 30 sec)
- minimal delay between 2 pictures, so no downloading of the image. Ideally the X-t1 should buffer the images, but that's outside of your control so not part of bounty.

PS: maybe money does not motivate you or it's not enough, in that case just do it for the project ;)
PPS: feel free to ask me questions if the scope is not clear

**Comment by hkr** [comment]
So far I only figured out how to adjust aperture and shutter speed relative to the current setting.
I'll push that in the next days

**Comment by mrosseel** [comment]
That might be enough, so you mean that the camera has some manual setting such as 1/4000 shutter speed, and you can say how much faster/slower you want? 

looking forward to your push!

**Comment by hkr** [comment]
Pushed.
Yeah, you set the camera to any manual shutter speed before you connect. Once connected you can adjust the shutter speed in using `shutter_speed 1` and `shutter_speed -1`.
Would be possible to implement `set_shutter_speed` `shutter_speed` and query of current shutter speed.

**Comment by mrosseel** [comment]
Checked it out last night, seems to work! Could you explain what the numbers are? +1 = +1/3 stop ?
The only problem I had was when sending 10 'shutter' commands to the camera, only 3 were processed and the rest was forgotten. 
* could you test multiple shutter commands and see why they are forgotten? 
* set_shutter_speed and shutter_speed would be nice, more intuitive for users

Have to test a bit more to see if it's really useable, but apart from the timing issue this seems already bounty-worthy ;)

**Comment by hkr** [comment]
Yeah the aperture changes are in +/- 1/3 f-stops.

I think to fix the "lost" shutter commands I'd have to wait until the previous one is complete. Had a look at old dumps again, I think it's possible to get that information including the picture ID on a separate socket connection. Will look into it...

**Comment by hkr** [comment]
`shutter` should now block until the next `shutter` is actually registered

**Comment by mrosseel** [comment]
great! Don't forget to push so I can test, thx

**Comment by hkr** [comment]
Added `set_aperture` and `set_shutter_speed`
Example:
`set_aperture 4`
`set_aperture 2.3`
`set_shutter_speed 1`
`set_shutter_speed 1/60`

If you pick a value that's not directly supported it should pick a close one, but the handling of that is not ideal, it doesn't pick the closest match.

**Comment by mrosseel** [comment]
Great work, pm me your paypal/bitcoin address because I think that bounty will be yours :)
One issue I'm having though, is that sometimes (this time it was the very first time), the tool just hangs after the first shutter command. Also, it's waiting on the thumbnail download which increases the minimum time between exposures - this would be bad for e.g. 5 bracket exposures, things can move if it takes 10-20 secs to take all exposures. As noted, it's possible this is a camera/sdk limitation.

![screen shot 2017-06-04 at 20 58 09](https://cloud.githubusercontent.com/assets/1465310/26764531/b2fe3efc-4968-11e7-8d9b-f893066d7df5.png)

**Comment by hkr** [comment]
Unfortunately I don't have a solution for these issues.
For the "hang" it could just be incomplete error handling in my code. but I haven't been able to reproduce it.

The camera only sends `CaptureComplete` (async3) if I request the thumbnail.
It seemed fine when I didn't setup the events connection at all, but then I obviously would also not get any `CaptureComplete` and the subsequent `shutter` might get lost.

The PIP spec mentions that burst mode may be supported, but I don't know if Fuji supports it.

**Comment by kernpanik** [comment]
> One issue I'm having though, is that sometimes (this time it was the very first time), the tool just hangs after the first shutter command.

Same here, both on the X-T10 and X70 -- not sometimes but always: First shot is taken and saved to the camera's SD card, but then the tool hangs at (thumbnail) and does not respond to further commands. 

The only thing to do is to interrupt the current command with [ctrl+c], which turns off the camera.

(macOS 10.12.6, latest Firmware on both Fuji cameras)
